apiVersion: v1
kind: Service
metadata:
  name: daddyjokes-depl
  namespace: daddyjokes-ns
  labels:
    app.kubernetes.io/name: daddyjokes-depl
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: daddyjokes-depl
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80